services:
  - type: web
    name: sashosha-math-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL
        value: "@sashoshamath"
      - key: SITE_URL
        value: "https://sashoshaa.github.io/sashosha-math/"
